name: Normalize

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      env:
        token: ${{ secrets.token }}
    - name: Export token to env
      run: |
        pip3 install PyGithub
    - name: Run Normalize Script
      run: |
        export GITHUB_TOKEN=${{ secrets.token }}
        python3 test.py